"""initial schema

Revision ID: 9d7ff9044b3e
Revises: 
Create Date: 2026-09-13 18:27:34.192073

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import game_companion.db.base as gcdb

revision: str = '9d7ff9044b3e'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('mode', sa.String(length=60), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'key', name='uq_encounter_key')
    )
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounters_game_id'), ['game_id'], unique=False)

    op.create_table('player_profiles',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_sources',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('last_checked_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'key', name='uq_source_key')
    )
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sources_game_id'), ['game_id'], unique=False)

    op.create_table('change_records',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_key', sa.String(length=120), nullable=False),
    sa.Column('detected_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('proposed_value', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('applied_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_records_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_records_review_status'), ['review_status'], unique=False)

    op.create_table('characters',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('duplication_level', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('last_verified_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_profile_id', 'key', name='uq_character_key')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('encounter_slots',
    sa.Column('encounter_id', sa.String(length=32), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'slot_index', name='uq_encounter_slot')
    )
    with op.batch_alter_table('encounter_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounter_slots_encounter_id'), ['encounter_id'], unique=False)

    op.create_table('player_preferences',
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_profile_id', 'scope', 'key', name='uq_player_pref_scope_key')
    )
    with op.batch_alter_table('player_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_preferences_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('redeem_codes',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('discovered_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('expires_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'code', name='uq_code')
    )
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_codes_game_id'), ['game_id'], unique=False)

    op.create_table('research_claims',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('retrieved_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_claims_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_claims_subject'), ['subject'], unique=False)

    op.create_table('resources',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('resource_key', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_profile_id', 'resource_key', name='uq_resource_key')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('screenshot_imports',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('screen_type', sa.String(length=60), nullable=False),
    sa.Column('screenshot_name', sa.String(length=255), nullable=True),
    sa.Column('screenshot_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('candidate', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('rejected_fields', sa.JSON(), nullable=False),
    sa.Column('applied_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshot_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshot_imports_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshot_imports_player_profile_id'), ['player_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshot_imports_status'), ['status'], unique=False)

    op.create_table('teams',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_profile_id', 'name', name='uq_team_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('training_goals',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_goals_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_goals_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('training_issues',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('character_keys', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_issues_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_issues_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('audit_results',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('checked_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_results_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_results_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('character_skills',
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('skill_key', sa.String(length=60), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'skill_key', name='uq_character_skill')
    )
    with op.batch_alter_table('character_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_skills_character_id'), ['character_id'], unique=False)

    op.create_table('combat_results',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('encounter_key', sa.String(length=80), nullable=False),
    sa.Column('encounter_slot', sa.String(length=40), nullable=True),
    sa.Column('played_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=True),
    sa.Column('team_snapshot', sa.JSON(), nullable=False),
    sa.Column('build_snapshot', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.String(length=40), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('cleared', sa.Boolean(), nullable=True),
    sa.Column('clear_time_seconds', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_results_encounter_key'), ['encounter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_results_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_results_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('equipment_items',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('refinement', sa.Integer(), nullable=True),
    sa.Column('equipped_character_id', sa.String(length=32), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('last_verified_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipped_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_items_equipped_character_id'), ['equipped_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_items_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_items_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('gear_items',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('set_key', sa.String(length=80), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('main_stat_key', sa.String(length=40), nullable=True),
    sa.Column('main_stat_value', sa.Float(), nullable=True),
    sa.Column('substats', sa.JSON(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('equipped_character_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('last_verified_at', gcdb.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipped_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gear_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gear_items_equipped_character_id'), ['equipped_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gear_items_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gear_items_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('player_code_states',
    sa.Column('code_id', sa.String(length=32), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['redeem_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id', 'player_profile_id', name='uq_code_player')
    )
    with op.batch_alter_table('player_code_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_code_states_code_id'), ['code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_code_states_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('resource_plan_entries',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('resource_key', sa.String(length=80), nullable=False),
    sa.Column('character_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_plan_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_plan_entries_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_plan_entries_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_plan_entries_player_profile_id'), ['player_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_plan_entries_resource_key'), ['resource_key'], unique=False)

    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'character_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    op.create_table('character_builds',
    sa.Column('game_id', sa.String(length=40), nullable=False),
    sa.Column('player_profile_id', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('equipment_item_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'name', name='uq_character_build_name')
    )
    with op.batch_alter_table('character_builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_builds_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_builds_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_builds_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('build_gear_slots',
    sa.Column('build_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('gear_item_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', gcdb.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gcdb.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['character_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gear_item_id'], ['gear_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'slot', name='uq_build_slot')
    )
    with op.batch_alter_table('build_gear_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_gear_slots_build_id'), ['build_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_gear_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_gear_slots_build_id'))

    op.drop_table('build_gear_slots')
    with op.batch_alter_table('character_builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_builds_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_character_builds_game_id'))
        batch_op.drop_index(batch_op.f('ix_character_builds_character_id'))

    op.drop_table('character_builds')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_character_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('resource_plan_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_plan_entries_resource_key'))
        batch_op.drop_index(batch_op.f('ix_resource_plan_entries_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_resource_plan_entries_game_id'))
        batch_op.drop_index(batch_op.f('ix_resource_plan_entries_character_id'))

    op.drop_table('resource_plan_entries')
    with op.batch_alter_table('player_code_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_code_states_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_player_code_states_code_id'))

    op.drop_table('player_code_states')
    with op.batch_alter_table('gear_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_items_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_gear_items_game_id'))
        batch_op.drop_index(batch_op.f('ix_gear_items_equipped_character_id'))

    op.drop_table('gear_items')
    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_items_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_items_game_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_items_equipped_character_id'))

    op.drop_table('equipment_items')
    with op.batch_alter_table('combat_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_results_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_combat_results_game_id'))
        batch_op.drop_index(batch_op.f('ix_combat_results_encounter_key'))

    op.drop_table('combat_results')
    with op.batch_alter_table('character_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_skills_character_id'))

    op.drop_table('character_skills')
    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_results_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_audit_results_game_id'))

    op.drop_table('audit_results')
    with op.batch_alter_table('training_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_issues_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_training_issues_game_id'))

    op.drop_table('training_issues')
    with op.batch_alter_table('training_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_goals_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_training_goals_game_id'))

    op.drop_table('training_goals')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_teams_game_id'))

    op.drop_table('teams')
    with op.batch_alter_table('screenshot_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshot_imports_status'))
        batch_op.drop_index(batch_op.f('ix_screenshot_imports_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_screenshot_imports_game_id'))

    op.drop_table('screenshot_imports')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_resources_game_id'))

    op.drop_table('resources')
    with op.batch_alter_table('research_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_claims_subject'))
        batch_op.drop_index(batch_op.f('ix_research_claims_game_id'))

    op.drop_table('research_claims')
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_codes_game_id'))

    op.drop_table('redeem_codes')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_game_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('player_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_preferences_player_profile_id'))

    op.drop_table('player_preferences')
    with op.batch_alter_table('encounter_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounter_slots_encounter_id'))

    op.drop_table('encounter_slots')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_player_profile_id'))
        batch_op.drop_index(batch_op.f('ix_characters_game_id'))

    op.drop_table('characters')
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_records_review_status'))
        batch_op.drop_index(batch_op.f('ix_change_records_game_id'))

    op.drop_table('change_records')
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_game_id'))

    op.drop_table('research_sources')
    op.drop_table('player_profiles')
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounters_game_id'))

    op.drop_table('encounters')
    # ### end Alembic commands ###
